### Get all blogs
GET http://localhost:3001/api/blogs

### Create new blog

POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "Test",
  "author": "Jorge",
  "url": "something.sfsdfdsd",
  "likes": 4
}
