### Get all blogs
GET http://localhost:3001/api/blogs

### Create new blog

POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "Another interesting blog",
  "author": "Someone",
  "url": "something.sfsdfdsd",
  "likes": 4
}

### Update a blog

PUT http://localhost:3001/api/blogs/5f3ebfd43068dd4a106f845c
Content-Type: application/json

{
  "title": "Another Test",
  "author": "testssssss",
  "url": "lalal.comfsdfs",
  "likes": 4
}